/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 31/10/2020 14:53:59          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

CREATE DATABASE 'D:\posto.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252 COLLATION WIN1252;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_BOMBA_ID;
SET GENERATOR GEN_BOMBA_ID TO 0;

CREATE GENERATOR GEN_COMBUSTIVEL_ID;
SET GENERATOR GEN_COMBUSTIVEL_ID TO 0;

CREATE GENERATOR GEN_FRENTISTA_ID;
SET GENERATOR GEN_FRENTISTA_ID TO 0;

CREATE GENERATOR GEN_TANQUE_ID;
SET GENERATOR GEN_TANQUE_ID TO 0;

CREATE GENERATOR GEN_VENDA_ID;
SET GENERATOR GEN_VENDA_ID TO 0;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE BOMBA (
    COD_BOMBA  INTEGER NOT NULL,
    DES_BOM    VARCHAR(15)
);

CREATE TABLE COMBUSTIVEL (
    COD_COMBUSTIVEL  INTEGER NOT NULL,
    DES_COMBUSTIVEL  VARCHAR(15),
    PRC_COMBUSTIVEL  DOUBLE PRECISION,
    IMPOSTO          DOUBLE PRECISION
);

CREATE TABLE FRENTISTA (
    COD_FRENTISTA  INTEGER NOT NULL,
    DES_FRENTISTA  VARCHAR(50)
);

CREATE TABLE TANQUE (
    COD_TANQUE  INTEGER NOT NULL,
    DES_TANQUE  VARCHAR(15),
    QTD_VOLUME  DOUBLE PRECISION
);

CREATE TABLE VENDA (
    COD_MOVIMENTO    INTEGER NOT NULL,
    DAT_MOVIMENTO    DATE NOT NULL,
    COD_TANQUE       INTEGER NOT NULL,
    COD_BOMBA        INTEGER NOT NULL,
    COD_COMBUSTIVEL  INTEGER NOT NULL,
    COD_FRENTISTA    INTEGER NOT NULL,
    QTD_LITRO        DOUBLE PRECISION NOT NULL,
    PRC_LITRO        DOUBLE PRECISION NOT NULL,
    IMPOSTO          DOUBLE PRECISION NOT NULL,
    VAL_IMPOSTO      DOUBLE PRECISION NOT NULL,
    VAL_VENDA        DOUBLE PRECISION NOT NULL
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE BOMBA ADD CONSTRAINT PK_BOMBA PRIMARY KEY (COD_BOMBA);
ALTER TABLE COMBUSTIVEL ADD CONSTRAINT PK_COMBUSTIVEL PRIMARY KEY (COD_COMBUSTIVEL);
ALTER TABLE FRENTISTA ADD CONSTRAINT PK_FRENTISTA PRIMARY KEY (COD_FRENTISTA);
ALTER TABLE TANQUE ADD CONSTRAINT PK_TANQUE PRIMARY KEY (COD_TANQUE);
ALTER TABLE VENDA ADD CONSTRAINT PK_VENDA PRIMARY KEY (COD_MOVIMENTO);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_BOMBA FOREIGN KEY (COD_BOMBA) REFERENCES BOMBA (COD_BOMBA) ON DELETE CASCADE;
ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_COMBUSTIVEL FOREIGN KEY (COD_COMBUSTIVEL) REFERENCES COMBUSTIVEL (COD_COMBUSTIVEL) ON DELETE CASCADE;
ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_FRENTISTA FOREIGN KEY (COD_FRENTISTA) REFERENCES FRENTISTA (COD_FRENTISTA) ON DELETE CASCADE;
ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_TANQUE FOREIGN KEY (COD_TANQUE) REFERENCES TANQUE (COD_TANQUE) ON DELETE CASCADE;
